/*
 * Car Rental API
 * API for managing cars and reservations in a car rental system.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Reservation model module.
 * @module model/Reservation
 * @version 1.0.0
 */
export default class Reservation {
  /**
   * Constructs a new <code>Reservation</code>.
   * @alias module:model/Reservation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Reservation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Reservation} obj Optional instance to populate.
   * @return {module:model/Reservation} The populated <code>Reservation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Reservation();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('carId'))
        obj.carId = ApiClient.convertToType(data['carId'], 'String');
      if (data.hasOwnProperty('customerName'))
        obj.customerName = ApiClient.convertToType(data['customerName'], 'String');
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Reservation.prototype.id = undefined;

/**
 * @member {String} carId
 */
Reservation.prototype.carId = undefined;

/**
 * @member {String} customerName
 */
Reservation.prototype.customerName = undefined;

/**
 * @member {Date} startDate
 */
Reservation.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
Reservation.prototype.endDate = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Reservation.StatusEnum = {
  /**
   * value: "pending"
   * @const
   */
  pending: "pending",

  /**
   * value: "confirmed"
   * @const
   */
  confirmed: "confirmed",

  /**
   * value: "canceled"
   * @const
   */
  canceled: "canceled"
};
/**
 * @member {module:model/Reservation.StatusEnum} status
 */
Reservation.prototype.status = undefined;

