/*
 * Car Rental API
 * API for managing cars and reservations in a car rental system.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarRentalApi);
  }
}(this, function(expect, CarRentalApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Reservation', function() {
      beforeEach(function() {
        instance = new CarRentalApi.Reservation();
      });

      it('should create an instance of Reservation', function() {
        // TODO: update the code to test Reservation
        expect(instance).to.be.a(CarRentalApi.Reservation);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property carId (base name: "carId")', function() {
        // TODO: update the code to test the property carId
        expect(instance).to.have.property('carId');
        // expect(instance.carId).to.be(expectedValueLiteral);
      });

      it('should have the property customerName (base name: "customerName")', function() {
        // TODO: update the code to test the property customerName
        expect(instance).to.have.property('customerName');
        // expect(instance.customerName).to.be(expectedValueLiteral);
      });

      it('should have the property startDate (base name: "startDate")', function() {
        // TODO: update the code to test the property startDate
        expect(instance).to.have.property('startDate');
        // expect(instance.startDate).to.be(expectedValueLiteral);
      });

      it('should have the property endDate (base name: "endDate")', function() {
        // TODO: update the code to test the property endDate
        expect(instance).to.have.property('endDate');
        // expect(instance.endDate).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

    });
  });

}));
