/*
 * Car Rental API
 * API for managing cars and reservations in a car rental system.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Car from './model/Car';
import Reservation from './model/Reservation';
import DefaultApi from './api/DefaultApi';

/**
* API_for_managing_cars_and_reservations_in_a_car_rental_system_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CarRentalApi = require('index'); // See note below*.
* var xxxSvc = new CarRentalApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CarRentalApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CarRentalApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CarRentalApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Car model constructor.
     * @property {module:model/Car}
     */
    Car,

    /**
     * The Reservation model constructor.
     * @property {module:model/Reservation}
     */
    Reservation,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
